#!/bin/sh
#
# Usage: tagrelease version
#

if [ -z "$1" ]; then
    echo "Usage: $0 version" 1>&2
    exit 1
fi

echo "$1" > version
git add version
git commit -m "NASM $1"
git tag -m "NASM $1" -a nasm-"$1"

