/* This file auto-generated from standard.mac by macros.pl - don't edit it */

static char *stdmac[] = {
    "%define __SECT__",
    "%imacro section 1+",
    "%define __SECT__ [section %1]",
    "__SECT__",
    "%endmacro",
    "%imacro segment 1+",
    "%define __SECT__ [segment %1]",
    "__SECT__",
    "%endmacro",
    "%imacro absolute 1+",
    "%define __SECT__ [absolute %1]",
    "__SECT__",
    "%endmacro",
    "%imacro struc 1",
    "%push struc",
    "%define %$strucname %1",
    "[absolute 0]",
    "%endmacro",
    "%imacro endstruc 0",
    "%{$strucname}_size:",
    "%pop",
    "__SECT__",
    "%endmacro",
    "%imacro extern 1+",
    "[extern %1]",
    "%endmacro",
    "%imacro bits 1+",
    "[bits %1]",
    "%endmacro",
    "%imacro global 1+",
    "[global %1]",
    "%endmacro",
    "%imacro common 1+",
    "[common %1]",
    "%endmacro",
    "%imacro org 1+",
    "[org %1]",
    "%endmacro",
    "%imacro group 1+",
    "[group %1]",
    "%endmacro",
    "%imacro uppercase 1+",
    "[uppercase %1]",
    "%endmacro",
    "%imacro library 1+",
    "[library %1]",
    "%endmacro",
    NULL
};
