#!/usr/bin/perl
#
# This adds SSE2AVX patterns to insns.xda
#

use integer;
use strict;

my($xdafile, $xd1file) = @ARGV;

open(my $xd1, '<', $xd1file) or die "$0: $xd1file: $!\n";

my %ops;
my $n = 0;
my @lines = ();

while (defined(my $l = <$xd1>)) {
    chomp $l;
    push(@lines, $l);
    my $n = $#lines;
    $l =~ s/^\s+//;
    $l =~ s/(?:\;.*|\s+)$//;
    next if ($l =~ /\bNOSSE2AVX\b/);
    if ($l =~ /^([A-Z]\S*)\s+((\S+).*)$/) {
	my $op = $1;
	my $args = $3;
	my $tail = $2;
	$args =~ s/[^,:]+\*,?//g;
	$args =~ s/\|[^,:]*//g;
	$ops{$op} = {} unless (defined($ops{$op}));
	$ops{$op}->{$args} = [] unless(defined($ops{$op}->{$args}));
	push(@{$ops{$op}->{$args}}, [$op, $n, $args, $tail]);
    }
}

close($xd1);

my @vlines;
foreach my $vop (sort grep (/^V/, keys(%ops))) {
    (my $op = $vop) =~ s/^V//;
    my $o = $ops{$op};
    my $v = $ops{$vop};
    if (defined($o)) {
	foreach my $args (keys (%$o)) {
	    my $ols = $o->{$args};
	    my $vls = $v->{$args};
	    if (defined($vls)) {
		push(@vlines, @$vls);
		foreach my $ol (@$ols) {
		    $lines[$ol->[1]] .= ',NOSSE2AVX';
		}
	    }
	}
    }
}

# Make sure to output the lines for each instruction in the same order
# they originally were listed in; this matters. For sanity's sake, however,
# sort the separate instructions.

open(my $xda, '>', $xdafile) or die "$0: $xdafile: $!\n";

foreach my $l (@lines) {
    print $xda $l, "\n";
}

print $xda "\n;\n; The following patterns were generated by sse2avx.pl\n;\n\n";

@vlines = sort { ($a->[0] cmp $b->[0]) || ($a->[1] <=> $b->[1]) } @vlines;
foreach my $vline (@vlines) {
    my($op, $n, $args, $tail) = @$vline;
    $op =~ s/^V//;
    printf $xda "%-23s %s,ND,SSE2AVX\n", $op, $tail;
}

close($xda);
